AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  PhythonCDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri:
        Bucket: phython-lambda-pipeline
        Key: !Sub 'LambdaCDDemo.zip'
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30     
      Role: 'arn:aws:iam::044387542557:role/service-role/codebuild-PhythonProject-service-role'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: ap-south-1
